plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish' // إضافة الإضافة للتعرف على أمر publishing
}

// تحديد المجموعة ورقم الإصدار للمكتبة
group = 'com.github.abdullghani'
version = '2.0.0'

android {
    namespace 'com.abdullghani.sheetflow'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        minSdk 21

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // إعداد حزمة AAR/Sources للنشر
    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

// إعدادات النشر لـ Maven / JitPack
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.abdullghani'
                artifactId = 'sheetflow'
                version = '2.0.0'
            }
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}